apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cassandra
  name: pvc-cassandra
spec:
  storageClassName: manual
  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
