version: 2

updates:
  - package-ecosystem: bundler
    allow:
      dependency_type: 'all'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    security-updates-only: true
    versioning-strategy: lockfile-only

  - package-ecosystem: npm
    allow:
      dependency_type: 'all'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    security-updates-only: true
    versioning-strategy: lockfile-only
